import "./globals.css";
import { Inter } from "next/font/google";

import { PollProvider } from "./_contexts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Multi Step Poll",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <PollProvider>
        <body className={inter.className}>{children}</body>
      </PollProvider>
    </html>
  );
}
